package com.chattcp.shared;

public enum MessageType {
    LOGIN, LOGIN_OK, LOGIN_FAIL,
    REGISTER, REGISTER_OK, REGISTER_FAIL,
    GROUP_CREATE, GROUP_JOIN, GROUP_LEAVE, GROUP_MESSAGE, GROUP_LIST,
    GROUP_ADD_MEMBER, GROUP_REMOVE_MEMBER,
    FRIEND_LIST,
    GROUP_DELETE,
    HISTORY_REQUEST, HISTORY_RESPONSE,
    LOGOUT,
    USER_LIST, // server -> clients: updated online list
    PRIVATE_MESSAGE,
    FILE_TRANSFER,
    FRIEND_REQUEST,
    FRIEND_RESPONSE,
    HEARTBEAT
}
